export const GET_POSTS = "GET_POSTS";
export const GET_POST_DETAIL = "GET_POST_DETAIL";
export const GET_LAST_POSTS = "GET_POSTS_LAST_POSTS";
export const GET_MOST_POPULAR_POSTS = "GET_MOST_POPULAR_POSTS";
export const GET_COMMENTS_BY_POST_ID = "GET_COMMENTS_BY_POST_ID";
